services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=db_main'  # Alterado para db_main
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_MULTIPLE_DATABASES=tenant1,tenant2'
      - 'POSTGRES_INITDB_ARGS=--encoding=UTF-8'
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./src/main/resources/db/changelog:/liquibase/changelog
    environment:
      - LIQUIBASE_HUB_MODE=off
    command: >
      --url=jdbc:postgresql://postgres:5432/db_main
      --username=postgres
      --password=postgres
      --changeLogFile=/liquibase/changelog/db.changelog-master.xml 
      --contexts=main
      update

    entrypoint: /bin/sh -c "
      liquibase --url=jdbc:postgresql://postgres:5432/db_main
      --username=postgres
      --password=postgres
      --changeLogFile=/liquibase/changelog/db.changelog-master.xml
      --contexts=main
      update &&
      for tenant in tenant1 tenant2; do
      liquibase --url=jdbc:postgresql://postgres:5432/db_main
      --username=postgres
      --password=postgres
      --changeLogFile=/liquibase/changelog/db.changelog-master.xml
      --defaultSchemaName=$$tenant
      --contexts=tenant
      update;
      done"

volumes:
  pg_data: